#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#


##
# Paths
##

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

# Set the the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )

# Set the list of directories that Zsh searches for programs.
path=(
    /usr/local/{bin,sbin}
    $path
)

# Node's install path
export NODE_PATH=/opt/lib/node_modules
export PATH="/usr/local/Cellar/emacs/24.5/bin:$PATH"
# Android SDK and tools setup
export ANDROID_HOME=~/Library/Android/sdk
export PATH=$PATH:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools
# Added by the Heroku Toolbelt
export PATH="/usr/local/heroku/bin:$PATH"
# GOlang
export PATH="$PATH:/usr/local/opt/go/libexec/bin"

##
# Settings
##
# fix emacs color issues
export TERM=xterm-256color
# leiningen
export LEIN_FAST_TRAMPOLINE=y


##
# Editors
##
export VISUAL='nano'
export PAGER='less'
export EDITOR='nano'


##
# Browser
##
if [[ "$OSTYPE" == darwin* ]]; then
    export BROWSER='open'
fi


##
# Language
##
if [[ -z "$LANG" ]]; then
    export LANG='en_US.UTF-8'
fi


##
# Less
##
# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-F -g -i -M -R -S -w -X -z-4'

# Use source-highlight for syntax highlighting in less
[ -f /usr/local/bin/src-hilite-lesspipe.sh ] && export LESSOPEN="| /usr/local/bin/src-hilite-lesspipe.sh %s"


##
# Temporary Files
##
if [[ ! -d "$TMPDIR" ]]; then
    export TMPDIR="/tmp/$LOGNAME"
    mkdir -p -m 700 "$TMPDIR"
fi

TMPPREFIX="${TMPDIR%/}/zsh"


# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ "$SHLVL" -eq 1 && ! -o LOGIN && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi
