#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

##
# Git
##
alias gcb='git checkout -b'
##
# Clojure
##
alias cljsbuild="lein trampoline cljsbuild $@"


##
# Ruby
##
alias be='bundle exec'


##
# Emacs
##
# start emacs server
alias es='emacs --daemon'

# NOTE: if alternate-editor is an empty string, Emacs is started in daemon mode and emacsclient will try to connect to it
# NOTE: the trailing '&' to run this as a background process doesn't work when an emacs daemon isn't running
# open emacs in a gui frame
function ec { emacsclient --alternate-editor='' -c $@ &; }

# start emacs in a terminal
alias et="emacsclient --alternate-editor='' -t"

# kill emacs server
alias ek="emacsclient -e '(kill-emacs)'"

# restart emacs server
alias er='ek; es;'

