#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi



# PERSONAL CUSTOMISATION....

##
# Git
##
unalias gs # for ghostscript
alias gstash='git stash'
alias gcb='git checkout -b'
alias gshm='git push heroku master'

##
# Clojure
##
alias cljsbuild="lein trampoline cljsbuild $@"


##
# Ruby
##
alias be='bundle exec'
# chruby setup
source /usr/local/share/chruby/chruby.sh
source /usr/local/share/chruby/auto.sh
chruby ruby-2.2.3 # Set default ruby version


##
# Terminal Markdown Viewer https://github.com/axiros/terminal_markdown_viewer
##
# Unfortunately buggy, but currently the best terminal markdown viewer for my needs
alias mdv='mdv -t "palette 99"'


##
# Emacs
##
# start emacs server
alias es='emacs --daemon'
# NOTE: if alternate-editor is an empty string, Emacs is started in daemon mode and emacsclient will try to connect to it
# open emacs in a gui frame
ec() { emacsclient --alternate-editor='' -c $@ &; }
# start emacs in a terminal
alias et="emacsclient --alternate-editor='' -t"
# kill emacs server
alias ek="emacsclient -e '(kill-emacs)'"
# restart emacs server
alias er='ek; es;'


##
# fasd & fzf
##
# smart jump with fzf and fasd
alias j=""
unalias j
j() {
    local dir
    dir="$(fasd -Rdl "$1" | fzf -1 -0 --no-sort +m)" && cd "${dir}" || return 1
}
# smart-open with emacsclient
v() {
    local file
    file="$(fasd -Rfl "$1" | fzf -1 -0 --no-sort +m)" && ec "${file}" || return 1
}
# smart-open with terminal emacs
vt() {
    local file
    file="$(fasd -Rfl "$1" | fzf -1 -0 --no-sort +m)" && et "${file}" || return 1
}
alias a='fasd -a'        # any
alias s='fasd -si'       # show / search / select
alias f='fasd -f'        # file
alias d='fasd -d'        # directory
alias sd='fasd -sid'     # interactive directory selection
alias sf='fasd -sif'     # interactive file selection
alias z='fasd_cd -d'     # cd, same functionality as j in autojump
alias o='a -e open'      # use fasd to select file/directory to open

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Dedicated completion key while retaining default TAB (^I) behaviour
export FZF_COMPLETION_TRIGGER=''
bindkey '^T' fzf-completion
# Use the fast the_platinum_surfer instead of find. Also respects .gitignore etc.
export FZF_DEFAULT_COMMAND='pt -l ""'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"

export NVM_DIR="/Users/cwhitey/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm
