#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# PERSONAL CUSTOMISATION....



##
# Git
##
alias gcb='git checkout -b'


##
# Clojure
##
alias cljsbuild="lein trampoline cljsbuild $@"


##
# Ruby
##
alias be='bundle exec'

# chruby setup
source /usr/local/share/chruby/chruby.sh
# source /usr/local/share/chruby/auto.sh # auto-switching prezto setting should do this for us
chruby ruby-2.1.2 # Set default ruby version


##
# Terminal Markdown Viewer https://github.com/axiros/terminal_markdown_viewer
##
# Unfortunately buggy, but currently the best terminal markdown viewer for my needs
alias mdv='mdv -t "palette 99"'


##
# Emacs
##
# start emacs server
alias es='emacs --daemon'

# NOTE: if alternate-editor is an empty string, Emacs is started in daemon mode and emacsclient will try to connect to it
# NOTE: the trailing '&' to run this as a background process doesn't work when an emacs daemon isn't running
# open emacs in a gui frame
function ec { emacsclient --alternate-editor='' -c $@ &; }

# start emacs in a terminal
alias et="emacsclient --alternate-editor='' -t"

# kill emacs server
alias ek="emacsclient -e '(kill-emacs)'"

# restart emacs server
alias er='ek; es;'


[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
